project:
  name: new-project
  tz: America/Chicago
  adrFolder: ./docs/adr
  packages:
    - name: package1
      path: ./packages/package1
      adrFolder: ./packages/package1/docs/adr
    - name: package2
      path: ./packages/package2
      adrFolder: ./packages/package2/docs/adr
  repository:
    url: https://github.com/auraspeed/adr # Absolute URL of your repository
    provider: github # Supported providers: github, gitlab, bitbucket. Use `generic` if yours is not supported
    viewFileUriPattern: /blob/main/%path
